package contentbuild

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"testing"
)

// These are immutable git 6a233279 bytes, not a response regenerated by either
// runtime. The manifest records each original path, length, digest and the
// independently recorded Source5 metadata against which all ten pins were checked.
const source5ContextArchive = "docs/reviews/v1-6-everyday-inputs/reference/historical-source5-context.tar.gz"
const source5ContextManifest = "docs/reviews/v1-6-everyday-inputs/reference/historical-source5-context-manifest.json"
const source5ContextArchiveSHA256 = "ffffa21ccf11f79d817c529123f2583824c62fefaabd17a5887e7ce809507e48"
const source5ContextManifestSHA256 = "47d93bbae6a5a6f5eec031a09568c20e2f81887598cff9fff9120c9eeff2a48c"

func readHistoricalContextFile(t *testing.T, name string, limit int64, digest string) []byte {
	t.Helper()
	f, err := os.Open(filepath.Join(repoRoot(t), filepath.FromSlash(name)))
	if err != nil {
		t.Fatal(err)
	}
	raw, err := io.ReadAll(io.LimitReader(f, limit+1))
	closeErr := f.Close()
	if err != nil || closeErr != nil || int64(len(raw)) > limit || SHA256(raw) != digest {
		t.Fatalf("historical context file identity or byte bound differs: %s (%v, %v)", name, err, closeErr)
	}
	return raw
}

func source5HistoricalRoot(t *testing.T) string {
	t.Helper()
	manifestRaw := readHistoricalContextFile(t, source5ContextManifest, 32<<10, source5ContextManifestSHA256)
	var manifest struct {
		Schema         string `json:"schema"`
		BaselineCommit string `json:"baseline_commit"`
		Entries        map[string]struct {
			Bytes  int64  `json:"bytes"`
			SHA256 string `json:"sha256"`
		} `json:"entries"`
	}
	if err := json.Unmarshal(manifestRaw, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest.Schema != "v1-6-immutable-source5-test-context-v1" || manifest.BaselineCommit != "6a2332795dc5fa2db3eb61e196ab7ab820e76caa" || len(manifest.Entries) != 12 {
		t.Fatal("historical context manifest provenance differs")
	}
	allowed := map[string]bool{
		"go-backend/internal/content/bundled.json":                               true,
		"go-backend/internal/content/digest.go":                                  true,
		"docs/CRITIQUE_RUBRIC.md":                                                true,
		"docs/reviews/v1-4-time-links-and-predicates/native/world/proposal.json": true,
	}
	for _, name := range SourceNames {
		allowed["cat_de_roman_esti/fixtures/"+name] = true
	}
	if len(allowed) != len(manifest.Entries) {
		t.Fatal("historical context source inventory differs")
	}
	compressed := readHistoricalContextFile(t, source5ContextArchive, 4<<20, source5ContextArchiveSHA256)
	z, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		t.Fatal(err)
	}
	rawTar, err := io.ReadAll(io.LimitReader(z, (32<<20)+1))
	closeErr := z.Close()
	if err != nil || closeErr != nil || len(rawTar) > 32<<20 {
		t.Fatal("historical context decompression or byte bound differs", err, closeErr)
	}
	files := make(map[string][]byte, len(manifest.Entries))
	archive := tar.NewReader(bytes.NewReader(rawTar))
	for {
		header, err := archive.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		want, known := manifest.Entries[header.Name]
		if !known || !allowed[header.Name] || files[header.Name] != nil || header.Typeflag != tar.TypeReg || header.Size != want.Bytes || header.Size < 1 || header.Size > 16<<20 {
			t.Fatalf("historical context archive member differs: %s", header.Name)
		}
		raw, err := io.ReadAll(io.LimitReader(archive, want.Bytes+1))
		if err != nil || int64(len(raw)) != want.Bytes || SHA256(raw) != want.SHA256 {
			t.Fatalf("historical context member bytes differ: %s (%v)", header.Name, err)
		}
		files[header.Name] = raw
	}
	if len(files) != len(manifest.Entries) {
		t.Fatal("historical context archive is incomplete")
	}
	bundle, err := decodeObject(files["go-backend/internal/content/bundled.json"])
	if err != nil {
		t.Fatal(err)
	}
	if SHA256(files["go-backend/internal/content/bundled.json"]) != "c1fff429992c69926aafb07f5b015f890a82c7c01cc5230107bdaf481bca5993" || SHA256(files["go-backend/internal/content/digest.go"]) != "35f33cfeb67f234ceeee6e2a6ec08dabc036a383e46bbd48bf6d8b4287061ea2" || len(object(bundle["sources"])) != 8 {
		t.Fatal("historical Source5 bundle/pin identity differs")
	}
	for _, name := range SourceNames {
		if TextSHA256(files["cat_de_roman_esti/fixtures/"+name]) != object(bundle["sources"])[name] {
			t.Fatalf("historical Source5 source binding differs: %s", name)
		}
	}
	root := t.TempDir()
	write := func(relative string, raw []byte) {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, raw, 0600); err != nil {
			t.Fatal(err)
		}
	}
	for name, raw := range files {
		write(name, raw)
	}
	for _, name := range []string{"kg_sample.json", "games_pack.json"} {
		write("tests/fixtures/"+name, files["cat_de_roman_esti/fixtures/"+name])
	}
	return root
}

// This test-only context admits exactly the old three reviewed pins while the
// real Build still reads and validates all eight immutable historical sources.
// Setenv deliberately marks the test as process-global: testing rejects this
// helper in a parallel test/ancestor and rejects a later t.Parallel call. The
// contentbuild tests have no background Build/Load goroutines. No current-source
// test can overlap this nonparallel context; cleanup restores the original map
// even after Fatal. Production Build/Load and their guards are unchanged.
func historicalSource45ReviewedPins(t *testing.T) {
	t.Helper()
	t.Setenv("CAT_CONTENTBUILD_HISTORICAL_TEST_CONTEXT", "source4-source5")
	previous := reviewedPins
	t.Cleanup(func() { reviewedPins = previous })
	reviewedPins = map[string]string{
		"derived_catalog_v38.json": "25059439b5c46a04263c229a8a3b9b4fc285240af60e15b7f1fdffa1a98f0c01",
		"quick_games_v92.json":     "a21b3c6e50be6947ea8b9ac181f337566db9e4809dd5165a203338fff20d8609",
		"release_reserve_v1.json":  "fd522b637ab87681d0e890ffb38de44fc57480bf37c302746a328d71a9219fb7",
	}
}

// Exercise restoration separately so later current-source tests cannot silently
// inherit historical authority, including when the package is run shuffled.
func TestHistoricalSource45ReviewedPinsRestore(t *testing.T) {
	previous := reviewedPins
	t.Run("historical scope", func(t *testing.T) {
		historicalSource45ReviewedPins(t)
		if len(reviewedPins) != 3 || reviewedPins["derived_catalog_v38.json"] != "25059439b5c46a04263c229a8a3b9b4fc285240af60e15b7f1fdffa1a98f0c01" || reviewedPins["quick_games_v92.json"] != "a21b3c6e50be6947ea8b9ac181f337566db9e4809dd5165a203338fff20d8609" || reviewedPins["release_reserve_v1.json"] != "fd522b637ab87681d0e890ffb38de44fc57480bf37c302746a328d71a9219fb7" {
			t.Fatal("historical reviewed pin scope differs")
		}
	})
	if len(reviewedPins) != len(previous) {
		t.Fatal("reviewed pins were not restored")
	}
	for name, digest := range previous {
		if reviewedPins[name] != digest {
			t.Fatalf("reviewed pin was not restored: %s", name)
		}
	}
}
