"""The vendored `/v1` client core must stay a faithful copy (romania_scraper ADR-0069).

`_roedu_client_core.py` is generated by the producer's
`scripts/sync_roedu_client.py`. These tests catch a local hand-edit (via the
embedded stamp) and pin the behaviour this app relies on — including the
repeated-cursor guard this app's previous private copy lacked.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from cat_de_roman_esti import roedu_client as public
from cat_de_roman_esti._roedu_client_core import (
    VENDORED_SHA256,
    RoeduClient,
    RoeduContractError,
)

CORE = Path(__file__).resolve().parents[1] / "cat_de_roman_esti/_roedu_client_core.py"


_BEGIN = "# --- BEGIN VENDORED romania_scraper/dataapi/roedu_client.py ---"
_END = "# --- END VENDORED ---"


def test_vendored_copy_has_not_been_hand_edited():
    """The stamp digests the region between the BEGIN/END markers, so any local
    edit to the client body changes the digest and fails here."""
    text = CORE.read_text(encoding="utf-8")
    body = text.split(_BEGIN, 1)[1].split(_END, 1)[0].strip("\n") + "\n"
    assert hashlib.sha256(body.encode("utf-8")).hexdigest() == VENDORED_SHA256, (
        "_roedu_client_core.py was edited locally; edit the canonical file in "
        "romania_scraper and re-run scripts/sync_roedu_client.py --write"
    )


def test_public_import_path_is_preserved():
    # cli.py and __init__.py import from .roedu_client; that must keep working.
    assert public.RoeduClient is RoeduClient
    assert public.RoeduContractError is RoeduContractError


class _FakeClient(RoeduClient):
    def __init__(self, pages):
        super().__init__(base_url="http://test", api_key="k")
        self._pages = list(pages)
        self.calls = 0

    def page(self, product, *, cursor=None, limit=200, **filters):  # noqa: ARG002
        self.calls += 1
        return self._pages[self.calls - 1]


def _page(records, *, next_cursor=None, available=True):
    body = {"available": available, "records": records}
    if next_cursor is not None:
        body["next_cursor"] = next_cursor
    return body


def test_repeated_cursor_no_longer_loops_forever():
    """The defect adopting the canonical core fixed: this app's own iter() had no
    cursor-repeat guard, so a server echoing one cursor spun indefinitely."""
    client = _FakeClient(
        [
            _page([{"id": "n1"}], next_cursor="c1"),
            _page([{"id": "n2"}], next_cursor="c1"),
        ]
    )
    with pytest.raises(RoeduContractError, match="repeated a pagination cursor"):
        list(client.iter("kg_nodes"))


def test_unavailable_page_is_still_fail_closed():
    client = _FakeClient([_page([{"id": "n1"}], available=False)])
    assert list(client.iter("kg_nodes")) == []


def test_cursor_following_and_max_records_unchanged():
    client = _FakeClient(
        [
            _page([{"id": "n1"}], next_cursor="c1"),
            _page([{"id": "n2"}]),
        ]
    )
    assert [r["id"] for r in client.iter("kg_nodes")] == ["n1", "n2"]

    capped = _FakeClient([_page([{"id": "a"}, {"id": "b"}, {"id": "c"}], next_cursor="c1")])
    assert len(list(capped.iter("kg_nodes", max_records=2))) == 2
