import * as fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { evaluate,gateBudgets } from '../budget/index.mjs';
const root=process.cwd(),target=process.argv[2];assert.ok(['unit','full'].includes(target));const out=path.join(root,'.gate',target);fs.mkdirSync(out,{recursive:true});
const run=(command,args,cwd=root)=>{const r=spawnSync(command,args,{cwd,env:process.env,encoding:'utf8',maxBuffer:32*1024*1024});if(r.stderr)process.stderr.write(r.stderr);assert.equal(r.status,0,`${command} actual exit: ${r.stdout}`);return r.stdout;};
run('npm',['run','build:sample']);
const assets=path.join(root,'web-kit/sample/embedfs/dist'),manifest=JSON.parse(fs.readFileSync(path.join(assets,'.vite/manifest.json'))),budgets=JSON.parse(fs.readFileSync('budgets.json'));
const binding=JSON.parse(fs.readFileSync('web-kit/sample/budget-bindings.json'));binding.global_css=[...new Set(manifest['src/sample/main.ts'].css??[])].sort();
const bindingsPath=path.join(out,'budget-bindings.json');fs.writeFileSync(bindingsPath,JSON.stringify(binding,null,2)+'\n');
const inventory=JSON.parse(run('go',['run','.','routes'],path.join(root,'web-kit/sample'))),routesPath=path.join(out,'budget-routes.json');fs.writeFileSync(routesPath,JSON.stringify(inventory,null,2)+'\n');
const node=evaluate(budgets,manifest,inventory,binding,assets),goPath=path.join(out,'budget-go.json');
run('go',['run','./cmd/budget','--budgets',path.join(root,'budgets.json'),'--manifest','.vite/manifest.json','--assets',assets,'--config',bindingsPath,'--routes',routesPath,'--out',goPath],path.join(root,'web-kit'));
const go=JSON.parse(fs.readFileSync(goPath)),rows=report=>[report.global_css,...report.routes.flatMap(r=>[r.js,r.css]),...(report.vendors??[])].map(row=>({scope:row.scope,name:row.name,actual_gz:row.actual_gz,limit_gz:row.limit_gz,status:row.status,files:row.files,target_gz:row.target_gz,target_status:row.target_status}));
assert.deepEqual(rows(node),rows(go),'Node/Go attribution of actual shipped gzip bytes agrees');assert.equal(node.status,'pass');
assert.throws(()=>evaluate(budgets,manifest,[],binding,assets));const incomplete=structuredClone(budgets);incomplete.routes={home:{class:'island-route',islands:binding.routes.home.islands,widgets:[]}};assert.throws(()=>evaluate(incomplete,manifest,inventory,binding,assets));
const bad=structuredClone(binding);bad.routes.home.limit_gz=99999999;assert.throws(()=>evaluate(budgets,manifest,inventory,bad,assets),'threshold override rejected');
const limited=structuredClone(budgets);limited.js['island-route'].limit_gz=0;assert.equal(evaluate(limited,manifest,inventory,binding,assets).status,'fail','same measured bytes fail tighter committed limit');
const before=createHash('sha256').update(fs.readFileSync('budgets.json')).digest('hex');
const measurement={schema:1,sha:process.env.GATE_SHA,tree_sha256:process.env.GATE_TREE_SHA256,methods:{bytes:'verified actual generated gzip sidecars',gzip_level:6},budgets_sha256:before,report:node,budgets:gateBudgets(node)};
fs.writeFileSync(path.join(out,'budget-measurements.json'),JSON.stringify(measurement,null,2)+'\n');console.log(JSON.stringify(measurement));
