# Generated by Django 5.2.15 on 2026-07-09 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('consent_completed', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, max_length=32)),
                ('is_minor', models.BooleanField(default=False)),
                ('parental_consent_required', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('privacy', 'Privacy notice'), ('tos', 'Terms of service')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('text_hash', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'document'], name='cat_account_user_id_c985db_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('detail', models.CharField(max_length=120)),
                ('at', models.BigIntegerField()),
                ('puzzle_key', models.CharField(blank=True, max_length=160)),
                ('daily', models.CharField(blank=True, max_length=10)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['user', 'game', '-at'], name='cat_account_user_id_26c73b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'at', 'puzzle_key'), name='uniq_user_run')],
            },
        ),
    ]
