# Generated by Django 5.2.15 on 2026-07-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_on_ranking',
            field=models.BooleanField(default=True),
        ),
    ]
