# Generated by Django 5.2.15 on 2026-07-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_accounts', '0002_profile_show_on_ranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('pack_id', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_played', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game'], name='cat_account_user_id_999685_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'pack_id'), name='uniq_user_played')],
            },
        ),
    ]
