# Generated by Django 5.2.15 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def make_rankings_private(apps, schema_editor):
    del schema_editor
    apps.get_model("cat_accounts", "Profile").objects.update(show_on_ranking=False)


class Migration(migrations.Migration):

    dependencies = [
        ("cat_accounts", "0003_playedpuzzle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="show_on_ranking",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(make_rankings_private, migrations.RunPython.noop),
        migrations.CreateModel(
            name="VerifiedBest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.CharField(max_length=20)),
                ("score", models.PositiveSmallIntegerField()),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cat_verified_bests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["game", "-score"],
                        name="cat_account_game_ee1c2d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "game"),
                        name="uniq_user_verified_game",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("game__in", (
                                "alchimie",
                                "intrusul",
                                "perechi",
                                "conexiuni",
                                "contexto",
                                "lant",
                            ))
                        ),
                        name="verified_game_allowlist",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1000)),
                        name="verified_score_bounds",
                    ),
                ],
            },
        ),
    ]
