"""Editorial source for the first shared Alchimie world; never loaded by serving.

Pairs express a recognisable culinary idea, not a complete cooking instruction.
The generated candidate artifact requires independent factual and quality review.
"""

WORLD = {
    "id": "bucataria-romaneasca-v1",
    "title": "Bucătăria românească",
    "description": (
        "Descoperă ingrediente și preparate, apoi folosește-le în combinații noi. "
        "Perechile surprind ideea unui preparat, nu întreaga rețetă de gătit."
    ),
}

# Reviewed presentation corrections; the original KG record remains in snapshot.
DESCRIPTIONS = {
    "Compot": ("Fructe fierte în apă, de obicei îndulcite; "
               "se consumă proaspăt sau se păstrează la borcan."),
    "Ardei umpluți": "Ardei umpluți cu orez, legume și uneori carne, fierți într-un sos.",
    "Sarmale": "Frunze de varză sau de viță umplute cu orez, legume și uneori carne.",
    "Paste": "Preparat din aluat de făină, cu apă sau ou, modelat și apoi fiert.",
}

STARTERS = ["Făină", "Apă", "Lapte", "Sare", "Cheag alimentar", "Mălai",
            "Cuptor de bucătărie", "Ou"]

UNLOCKS = [
    ("camara", 3, "Se deschide cămara", [
        "Fruct", "Zahăr", "Lămâie", "Castravete", "Legume",
    ]),
    ("pranz", 8, "Ingrediente pentru prânz", [
        "Usturoi", "Orez", "Ardei", "Carne", "Borș", "Fasole", "Roșie",
    ]),
    ("cofetarie", 16, "Atelierul de dulciuri", [
        "Unt", "Smântână", "Smântână dulce pentru frișcă", "Mixer de bucătărie",
        "Vanilie", "Cacao", "Lapte praf", "Nucă", "Măr", "Griș",
    ]),
    ("sarbatoare", 24, "Pentru o masă de sărbătoare", [
        "Congelator", "Stafide", "Gelatină alimentară", "Pișcot",
        "Varză murată", "Ulei",
    ]),
]

# id, ingredient A, ingredient B, result, short original explanation.
# Sources below are reference entry points, individually verified by the factual reviewer.
RECIPES = [
    ("aluat-apa", "Făină", "Apă", "Aluat",
     "Făina amestecată și frământată cu apă formează un aluat simplu."),
    ("aluat-lapte", "Făină", "Lapte", "Aluat",
     "Laptele poate înlocui apa în aluaturi; frământarea leagă făina cu lichidul."),
    ("paste-ou", "Făină", "Ou", "Paste",
     "Făina și oul formează aluatul de paste proaspete, întins și tăiat apoi."),
    ("paste-aluat", "Aluat", "Ou", "Paste",
     "Un aluat cu ou, întins subțire și tăiat, devine paste de casă."),
    ("pandispan-ou-zahar", "Ou", "Zahăr", "Pandișpan",
     "Ouăle bătute cu zahăr dau baza unui pandișpan; se încorporează făină și se coace."),
    ("paine-cuptor", "Aluat", "Cuptor de bucătărie", "Pâine",
     "Aluatul de pâine se coace în cuptor; dospirea depinde de sortiment."),
    ("branza-cheag", "Lapte", "Cheag alimentar", "Brânză",
     "Cheagul coagulează laptele; prin scurgerea zerului se obține brânza."),
    ("branza-lamaie", "Lapte", "Lămâie", "Brânză",
     "Zeama de lămâie poate coagula laptele încălzit pentru o brânză proaspătă."),
    ("saramura", "Apă", "Sare", "Saramură",
     "Sarea dizolvată în apă formează saramură."),
    ("mamaliga-apa", "Mălai", "Apă", "Mămăligă",
     "Mălaiul fiert în apă și amestecat devine mămăligă."),
    ("mamaliga-lapte", "Mălai", "Lapte", "Mămăligă",
     "Există și mămăligă fiartă în lapte, în loc de apă sau împreună cu aceasta."),
    ("telemea", "Brânză", "Saramură", "Telemea",
     "Telemeaua este o brânză care se sărează și se păstrează în saramură."),
    ("bulz-branza", "Mămăligă", "Brânză", "Bulz",
     "Mămăliga umplută cu brânză și coaptă formează bulzul."),
    ("bulz-telemea", "Mămăligă", "Telemea", "Bulz",
     "Telemeaua poate umple un bulz de mămăligă, copt apoi."),
    ("dulceata-fruct", "Fruct", "Zahăr", "Dulceață",
     "Fructele fierte cu zahăr dau dulceață; timpul și proporțiile depind de fruct."),
    ("dulceata-mar", "Măr", "Zahăr", "Dulceață",
     "Bucățile de măr se pot fierbe în sirop de zahăr pentru dulceață de mere."),
    ("compot-fruct", "Fruct", "Apă", "Compot",
     "Fructele fierte în apă formează compot, îndulcit după gust."),
    ("compot-mar", "Măr", "Apă", "Compot",
     "Merele fierte în apă dau compot de mere, cu zahăr după gust."),
    ("muraturi-legume", "Legume", "Saramură", "Murături",
     "Legumele se pot conserva prin fermentare în saramură."),
    ("castraveti-saramura", "Castravete", "Saramură", "Castraveți murați",
     "Castraveții ținuți în saramură fermentează și devin castraveți murați."),
    ("supa-legume", "Legume", "Apă", "Supă",
     "Legumele fierte în apă dau baza unei supe de legume."),
    ("ciorba-bors", "Supă", "Borș", "Ciorbă",
     "Borșul acrește o supă de legume sau carne, transformând-o într-o ciorbă."),
    ("ciorba-fasole", "Ciorbă", "Fasole", "Ciorbă de fasole",
     "Fasolea fiartă este ingredientul principal al ciorbei de fasole."),
    ("ciorba-fasole-bors", "Fasole", "Borș", "Ciorbă de fasole",
     "Fasolea fiartă cu legume se poate acri cu borș pentru ciorbă de fasole."),
    ("mujdei", "Usturoi", "Apă", "Mujdei",
     "Usturoiul zdrobit, frecat cu sare și diluat cu apă dă un mujdei simplu."),
    ("mujdei-ulei", "Usturoi", "Ulei", "Mujdei",
     "Usturoiul zdrobit poate fi frecat cu ulei pentru un mujdei cremos."),
    ("fasole-batuta", "Fasole", "Usturoi", "Fasole bătută",
     "Fasolea fiartă, pasată și aromatizată cu usturoi formează fasole bătută."),
    ("ardei-orez", "Ardei", "Orez", "Ardei umpluți",
     "Ardeii se pot umple cu orez și legume pentru o variantă de post."),
    ("ardei-carne", "Ardei", "Carne", "Ardei umpluți",
     "Ardeii umpluți pot avea o compoziție cu carne tocată, orez și condimente."),
    ("friptura-cuptor", "Carne", "Cuptor de bucătărie", "Friptură",
     "Carnea pregătită și coaptă în cuptor devine friptură."),
    ("salata", "Roșie", "Castravete", "Salată",
     "Roșiile și castraveții tăiați sunt baza unei salate proaspete de vară."),
    ("branza-smantana", "Brânză", "Smântână", "Brânză cu smântână",
     "Brânza proaspătă se poate amesteca și servi cu smântână."),
    ("frisca-mixer", "Smântână dulce pentru frișcă", "Mixer de bucătărie", "Frișcă",
     "Smântâna dulce rece, potrivită pentru bătut, devine frișcă folosind mixerul."),
    ("crema-vanilie", "Lapte", "Vanilie", "Cremă de vanilie",
     "Laptele aromatizat cu vanilie este baza cremei, îngroșată cu ou sau amidon."),
    ("crema-ou", "Ou", "Vanilie", "Cremă de vanilie",
     "Oul și vanilia intră în crema de vanilie, preparată cu lapte și zahăr."),
    ("ciocolata-casa", "Cacao", "Lapte praf", "Ciocolată",
     "Cacaua și laptele praf formează ciocolata de casă împreună cu sirop de zahăr și unt."),
    ("biscuit-unt", "Făină", "Unt", "Biscuit",
     "Făina și untul formează baza biscuiților fragezi, cu zahăr și coacere."),
    ("salam-cacao", "Biscuit", "Cacao", "Salam de biscuiți",
     "Biscuiții rupți și cacaua sunt ingredientele caracteristice ale salamului de biscuiți."),
    ("salam-ciocolata", "Biscuit", "Ciocolată", "Salam de biscuiți",
     "O variantă de salam de biscuiți leagă biscuiții cu o compoziție de ciocolată."),
    ("placinta-mere", "Aluat", "Măr", "Plăcintă cu mere",
     "Foile de aluat învelesc umplutura de mere pentru plăcinta cu mere."),
    ("cozonac-nuca", "Aluat", "Nucă", "Cozonac",
     "Aluatul dulce dospit și umplutura de nucă alcătuiesc cozonacul cu nucă."),
    ("cozonac-cacao", "Aluat", "Cacao", "Cozonac",
     "Cacaua poate aromatiza umplutura unui cozonac din aluat dulce dospit."),
    ("papanasi-faina", "Brânză", "Făină", "Papanași",
     "Brânza proaspătă și făina intră în aluatul de papanași, alături de ou."),
    ("papanasi-gris", "Brânză", "Griș", "Papanași",
     "Papanașii fierți pot lega brânza proaspătă cu griș și ou."),
    ("supa-galuste", "Supă", "Griș", "Supă cu găluște",
     "Găluștele din griș și ou se fierb în supă pentru supă cu găluște."),
    ("cremsnit", "Aluat", "Cremă de vanilie", "Cremșnit",
     "Foile coapte de foietaj, un tip de aluat, se umplu cu cremă de vanilie pentru cremșnit."),
    ("poale-brau", "Aluat", "Brânză", "Poale-n brâu",
     "Poalele-n brâu sunt plăcinte din aluat dospit, împăturite peste brânză dulce."),
    ("inghetata-frisca", "Frișcă", "Congelator", "Înghețată",
     "O bază îndulcită cu frișcă, congelată, poate deveni înghețată de casă."),
    ("inghetata-crema", "Cremă de vanilie", "Congelator", "Înghețată",
     "O cremă de vanilie potrivită poate fi răcită și congelată ca bază de înghețată."),
    ("diplomat-piscot", "Frișcă", "Pișcot", "Tort Diplomat",
     "Tortul Diplomat poate avea pișcoturi și o cremă cu frișcă, fructe și gelatină."),
    ("diplomat-gelatina", "Frișcă", "Gelatină alimentară", "Tort Diplomat",
     "Frișca și gelatina intră în crema de Diplomat, împreună cu ou, lapte și fructe."),
    ("pasca-stafide", "Brânză", "Stafide", "Pască",
     "Brânza dulce și stafidele formează umplutura clasică a unei păști."),
    ("amandina-cacao", "Pandișpan", "Cacao", "Amandină",
     "Amandina pornește de la un blat de pandișpan cu cacao, completat cu sirop și cremă."),
    ("amandina-ciocolata", "Pandișpan", "Ciocolată", "Amandină",
     "O amandină poate avea blat de pandișpan cu cacao și cremă sau glazură de ciocolată."),
    ("sarmale-carne", "Varză murată", "Carne", "Sarmale",
     "Frunzele de varză murată învelesc umplutura de carne, orez și condimente a sarmalelor."),
    ("sarmale-orez", "Varză murată", "Orez", "Sarmale",
     "Sarmalele de post pot avea orez și legume învelite în frunze de varză murată."),
    ("gogosi", "Aluat", "Ulei", "Gogoși",
     "Bucățile de aluat dospit, prăjite în ulei și îndulcite, devin gogoși."),
]

GOALS = [
    ("paine", "Pâine", "Prima pâine"),
    ("bulz", "Bulz", "Gust de stână"),
    ("muraturi", "Murături", "Cămara pentru iarnă"),
    ("ciorba-fasole", "Ciorbă de fasole", "O ciorbă de casă"),
    ("cozonac", "Cozonac", "Cozonacul de sărbătoare"),
    ("papanasi", "Papanași", "Papanași pentru desert"),
    ("inghetata", "Înghețată", "Un desert rece"),
    ("diplomat", "Tort Diplomat", "Tortul de sărbătoare"),
    ("sarmale", "Sarmale", "Sarmale pentru masă"),
]
