"""Editorial source for the shared Alchimie kitchen world; never loaded by serving.

Pairs express a recognisable culinary idea, not a complete cooking instruction.
The generated candidate artifact requires independent factual and quality review.
"""

WORLD = {
    "id": "bucataria-romaneasca-v1",
    "title": "Bucătăria românească",
    "description": (
        "Descoperă ingrediente și preparate, apoi folosește-le în combinații noi. "
        "Perechile surprind ideea unui preparat, nu întreaga rețetă de gătit."
    ),
}

# Reviewed presentation corrections; the original KG record remains in snapshot.
DESCRIPTIONS = {
    "Compot": ("Fructe fierte în apă, de obicei îndulcite; "
               "se consumă proaspăt sau se păstrează la borcan."),
    "Ardei umpluți": "Ardei umpluți cu orez, legume și uneori carne, fierți într-un sos.",
    "Sarmale": "Frunze de varză sau de viță umplute cu orez, legume și uneori carne.",
    "Paste": "Preparat din aluat de făină, cu apă sau ou, modelat și apoi fiert.",
    "Tigaie": "Vas puțin adânc, folosit pentru prăjit și rumenit alimente.",
    "Cartof": "Tubercul comestibil, gătit prin fierbere, coacere sau prăjire.",
    "Ceapă": "Legumă cu bulb, folosită crudă sau gătită pentru gust și aromă.",
    "Miere": "Produs dulce făcut de albine din nectar sau mană.",
    "Scorțișoară": "Condiment aromat din scoarța unor arbori, folosit mai ales în deserturi.",
    "Semințe de floarea-soarelui": "Semințe cu miez comestibil, folosite și la halva sau ulei.",
    "Cașcaval": "Brânză cu pastă opărită, folosită în sandvișuri și preparate calde.",
    "Prună": "Fruct cu sâmbure, folosit proaspăt, în compoturi, dulcețuri și plăcinte.",
    "Căpșună": "Fruct roșu și aromat, consumat proaspăt sau în deserturi și conserve.",
    "Dovleac": "Plantă cu fruct mare; soiurile comestibile se folosesc și la plăcinte.",
    "Untură": "Grăsime animală topită și strecurată, folosită inclusiv în aluaturi fragede.",
    "Zer": "Lichid rămas după coagularea și scurgerea laptelui, folosit și la urdă.",
    "Oală": "Vas adânc pentru fierberea și gătirea alimentelor.",
    "Arpacaș": "Boabe de cereale decorticate, folosite fierte în diferite preparate.",
    "Iaurt": "Produs obținut prin fermentarea laptelui cu culturi de bacterii lactice.",
    "Grătar": "Mod de a frige alimente pe un suport încins, deasupra unei surse de căldură.",
    "Sandviș": "Gustare cu pâine și o umplutură sau un strat de ingrediente.",
    "Clătite": "Foi subțiri din aluat fluid, coapte în tigaie și servite dulci sau sărate.",
    "Pizza": "Preparat copt din aluat întins, acoperit cu sos, brânză și alte ingrediente.",
    "Cartofi prăjiți": "Bucăți de cartof prăjite în ulei sau altă grăsime.",
    "Șnițel": "Felie subțire de carne, de obicei acoperită cu făină, ou și pesmet, apoi prăjită.",
    "Chiftele": "Porții modelate din carne tocată sau legume, apoi prăjite ori coapte.",
    "Frigărui": "Bucăți de carne, legume sau alte alimente înșirate pe bețe și fripte.",
    "Ciorbă de perișoare": "Ciorbă cu mici bile din carne tocată, de obicei legată cu orez și ou.",
    "Piftie": "Preparat rece din carne și zeamă de carne închegată, aromatizat adesea cu usturoi.",
    "Zacuscă": "Preparat de legume gătite, adesea cu ardei, ceapă, roșii și vinete sau fasole.",
    "Urdă": "Produs lactat obținut prin încălzirea zerului și adunarea proteinelor coagulate.",
    "Mucenici": ("Preparate în formă de opt pentru 9 martie: copți și unși cu miere în "
                 "varianta moldovenească, fierți în zeamă dulce în cea muntenească."),
    "Alivenci": "Preparat moldovenesc copt din mălai și lactate, în variante dulci sau sărate.",
    "Cornulețe": "Fursecuri fragede modelate ca mici cornuri, cu umplutură dulce.",
    "Turtă dulce": "Prăjitură aromată cu miere sau sirop și condimente, precum scorțișoara.",
    "Halva": "Preparat dulce din semințe măcinate și o compoziție îndulcită.",
    "Colivă": "Preparat din grâu sau arpacaș fiert, îndulcit și amestecat de obicei cu nucă.",
    "Firimitură": ("Bucățică mică de pâine sau alt aliment; "
                   "pâinea uscată se poate mărunți pentru pesmet."),
    "Cașcaval pane": "Felii de cașcaval acoperite cu făină, ou și pesmet, apoi prăjite.",
    "Plăcinte": "Preparate din aluat cu umplutură dulce sau sărată, coapte ori prăjite.",
}

STARTERS = ["Făină", "Apă", "Lapte", "Sare", "Cheag alimentar", "Mălai",
            "Cuptor de bucătărie", "Ou"]

UNLOCKS = [
    ("camara", 3, "Se deschide cămara", [
        "Fruct", "Zahăr", "Lămâie", "Castravete", "Legume",
    ]),
    ("pranz", 8, "Ingrediente pentru prânz", [
        "Usturoi", "Orez", "Ardei", "Carne", "Borș", "Fasole", "Roșie",
    ]),
    ("cofetarie", 16, "Atelierul de dulciuri", [
        "Unt", "Smântână", "Smântână dulce pentru frișcă", "Mixer de bucătărie",
        "Vanilie", "Cacao", "Lapte praf", "Nucă", "Măr", "Griș",
    ]),
    ("sarbatoare", 24, "Pentru o masă de sărbătoare", [
        "Congelator", "Stafide", "Gelatină alimentară", "Pișcot",
        "Varză murată", "Ulei",
    ]),
    ("gustari", 30, "Gustări și preparate la tigaie", [
        "Tigaie", "Cartof", "Ceapă", "Cașcaval", "Grătar", "Iaurt", "Firimitură",
    ]),
    ("traditii", 36, "Mai departe prin cămară", [
        "Miere", "Scorțișoară", "Semințe de floarea-soarelui", "Prună", "Căpșună",
        "Dovleac", "Untură", "Zer", "Oală", "Arpacaș",
    ]),
]

# id, ingredient A, ingredient B, result, short original explanation.
# Sources below are reference entry points, individually verified by the factual reviewer.
RECIPES = [
    ("aluat-apa", "Făină", "Apă", "Aluat",
     "Făina amestecată și frământată cu apă formează un aluat simplu."),
    ("aluat-lapte", "Făină", "Lapte", "Aluat",
     "Laptele poate înlocui apa în aluaturi; frământarea leagă făina cu lichidul."),
    ("paste-ou", "Făină", "Ou", "Paste",
     "Făina și oul formează aluatul de paste proaspete, întins și tăiat apoi."),
    ("paste-aluat", "Aluat", "Ou", "Paste",
     "Un aluat cu ou, întins subțire și tăiat, devine paste de casă."),
    ("pandispan-ou-zahar", "Ou", "Zahăr", "Pandișpan",
     "Ouăle bătute cu zahăr dau baza unui pandișpan; se încorporează făină și se coace."),
    ("paine-cuptor", "Aluat", "Cuptor de bucătărie", "Pâine",
     "Aluatul de pâine se coace în cuptor; dospirea depinde de sortiment."),
    ("branza-cheag", "Lapte", "Cheag alimentar", "Brânză",
     "Cheagul coagulează laptele; prin scurgerea zerului se obține brânza."),
    ("branza-lamaie", "Lapte", "Lămâie", "Brânză",
     "Zeama de lămâie poate coagula laptele încălzit pentru o brânză proaspătă."),
    ("saramura", "Apă", "Sare", "Saramură",
     "Sarea dizolvată în apă formează saramură."),
    ("mamaliga-apa", "Mălai", "Apă", "Mămăligă",
     "Mălaiul fiert în apă și amestecat devine mămăligă."),
    ("mamaliga-lapte", "Mălai", "Lapte", "Mămăligă",
     "Există și mămăligă fiartă în lapte, în loc de apă sau împreună cu aceasta."),
    ("telemea", "Brânză", "Saramură", "Telemea",
     "Telemeaua este o brânză care se sărează și se păstrează în saramură."),
    ("bulz-branza", "Mămăligă", "Brânză", "Bulz",
     "Mămăliga umplută cu brânză și coaptă formează bulzul."),
    ("bulz-telemea", "Mămăligă", "Telemea", "Bulz",
     "Telemeaua poate umple un bulz de mămăligă, copt apoi."),
    ("dulceata-fruct", "Fruct", "Zahăr", "Dulceață",
     "Fructele fierte cu zahăr dau dulceață; timpul și proporțiile depind de fruct."),
    ("dulceata-mar", "Măr", "Zahăr", "Dulceață",
     "Bucățile de măr se pot fierbe în sirop de zahăr pentru dulceață de mere."),
    ("compot-fruct", "Fruct", "Apă", "Compot",
     "Fructele fierte în apă formează compot, îndulcit după gust."),
    ("compot-mar", "Măr", "Apă", "Compot",
     "Merele fierte în apă dau compot de mere, cu zahăr după gust."),
    ("muraturi-legume", "Legume", "Saramură", "Murături",
     "Legumele se pot conserva prin fermentare în saramură."),
    ("castraveti-saramura", "Castravete", "Saramură", "Castraveți murați",
     "Castraveții ținuți în saramură fermentează și devin castraveți murați."),
    ("supa-legume", "Legume", "Apă", "Supă",
     "Legumele fierte în apă dau baza unei supe de legume."),
    ("ciorba-bors", "Supă", "Borș", "Ciorbă",
     "Borșul acrește o supă de legume sau carne, transformând-o într-o ciorbă."),
    ("ciorba-fasole", "Ciorbă", "Fasole", "Ciorbă de fasole",
     "Fasolea fiartă este ingredientul principal al ciorbei de fasole."),
    ("ciorba-fasole-bors", "Fasole", "Borș", "Ciorbă de fasole",
     "Fasolea fiartă cu legume se poate acri cu borș pentru ciorbă de fasole."),
    ("mujdei", "Usturoi", "Apă", "Mujdei",
     "Usturoiul zdrobit, frecat cu sare și diluat cu apă dă un mujdei simplu."),
    ("mujdei-ulei", "Usturoi", "Ulei", "Mujdei",
     "Usturoiul zdrobit poate fi frecat cu ulei pentru un mujdei cremos."),
    ("fasole-batuta", "Fasole", "Usturoi", "Fasole bătută",
     "Fasolea fiartă, pasată și aromatizată cu usturoi formează fasole bătută."),
    ("ardei-orez", "Ardei", "Orez", "Ardei umpluți",
     "Ardeii se pot umple cu orez și legume pentru o variantă de post."),
    ("ardei-carne", "Ardei", "Carne", "Ardei umpluți",
     "Ardeii umpluți pot avea o compoziție cu carne tocată, orez și condimente."),
    ("friptura-cuptor", "Carne", "Cuptor de bucătărie", "Friptură",
     "Carnea pregătită și coaptă în cuptor devine friptură."),
    ("salata", "Roșie", "Castravete", "Salată",
     "Roșiile și castraveții tăiați sunt baza unei salate proaspete de vară."),
    ("branza-smantana", "Brânză", "Smântână", "Brânză cu smântână",
     "Brânza proaspătă se poate amesteca și servi cu smântână."),
    ("frisca-mixer", "Smântână dulce pentru frișcă", "Mixer de bucătărie", "Frișcă",
     "Smântâna dulce rece, potrivită pentru bătut, devine frișcă folosind mixerul."),
    ("crema-vanilie", "Lapte", "Vanilie", "Cremă de vanilie",
     "Laptele aromatizat cu vanilie este baza cremei, îngroșată cu ou sau amidon."),
    ("crema-ou", "Ou", "Vanilie", "Cremă de vanilie",
     "Oul și vanilia intră în crema de vanilie, preparată cu lapte și zahăr."),
    ("ciocolata-casa", "Cacao", "Lapte praf", "Ciocolată",
     "Cacaua și laptele praf formează ciocolata de casă împreună cu sirop de zahăr și unt."),
    ("biscuit-unt", "Făină", "Unt", "Biscuit",
     "Făina și untul formează baza biscuiților fragezi, cu zahăr și coacere."),
    ("salam-cacao", "Biscuit", "Cacao", "Salam de biscuiți",
     "Biscuiții rupți și cacaua sunt ingredientele caracteristice ale salamului de biscuiți."),
    ("salam-ciocolata", "Biscuit", "Ciocolată", "Salam de biscuiți",
     "O variantă de salam de biscuiți leagă biscuiții cu o compoziție de ciocolată."),
    ("placinta-mere", "Aluat", "Măr", "Plăcintă cu mere",
     "Foile de aluat învelesc umplutura de mere pentru plăcinta cu mere."),
    ("cozonac-nuca", "Aluat", "Nucă", "Cozonac",
     "Aluatul dulce dospit și umplutura de nucă alcătuiesc cozonacul cu nucă."),
    ("cozonac-cacao", "Aluat", "Cacao", "Cozonac",
     "Cacaua poate aromatiza umplutura unui cozonac din aluat dulce dospit."),
    ("papanasi-faina", "Brânză", "Făină", "Papanași",
     "Brânza proaspătă și făina intră în aluatul de papanași, alături de ou."),
    ("papanasi-gris", "Brânză", "Griș", "Papanași",
     "Papanașii fierți pot lega brânza proaspătă cu griș și ou."),
    ("supa-galuste", "Supă", "Griș", "Supă cu găluște",
     "Găluștele din griș și ou se fierb în supă pentru supă cu găluște."),
    ("cremsnit", "Aluat", "Cremă de vanilie", "Cremșnit",
     "Foile coapte de foietaj, un tip de aluat, se umplu cu cremă de vanilie pentru cremșnit."),
    ("poale-brau", "Aluat", "Brânză", "Poale-n brâu",
     "Poalele-n brâu sunt plăcinte din aluat dospit, împăturite peste brânză dulce."),
    ("inghetata-frisca", "Frișcă", "Congelator", "Înghețată",
     "O bază îndulcită cu frișcă, congelată, poate deveni înghețată de casă."),
    ("inghetata-crema", "Cremă de vanilie", "Congelator", "Înghețată",
     "O cremă de vanilie potrivită poate fi răcită și congelată ca bază de înghețată."),
    ("diplomat-piscot", "Frișcă", "Pișcot", "Tort Diplomat",
     "Tortul Diplomat poate avea pișcoturi și o cremă cu frișcă, fructe și gelatină."),
    ("diplomat-gelatina", "Frișcă", "Gelatină alimentară", "Tort Diplomat",
     "Frișca și gelatina intră în crema de Diplomat, împreună cu ou, lapte și fructe."),
    ("pasca-stafide", "Brânză", "Stafide", "Pască",
     "Brânza dulce și stafidele formează umplutura clasică a unei păști."),
    ("amandina-cacao", "Pandișpan", "Cacao", "Amandină",
     "Amandina pornește de la un blat de pandișpan cu cacao, completat cu sirop și cremă."),
    ("amandina-ciocolata", "Pandișpan", "Ciocolată", "Amandină",
     "O amandină poate avea blat de pandișpan cu cacao și cremă sau glazură de ciocolată."),
    ("sarmale-carne", "Varză murată", "Carne", "Sarmale",
     "Frunzele de varză murată învelesc umplutura de carne, orez și condimente a sarmalelor."),
    ("sarmale-orez", "Varză murată", "Orez", "Sarmale",
     "Sarmalele de post pot avea orez și legume învelite în frunze de varză murată."),
    ("gogosi", "Aluat", "Ulei", "Gogoși",
     "Bucățile de aluat dospit, prăjite în ulei și îndulcite, devin gogoși."),
    ("sandvis-branza", "Pâine", "Brânză", "Sandviș",
     "Brânza pusă pe pâine sau între două felii formează un sandviș simplu."),
    ("sandvis-telemea", "Pâine", "Telemea", "Sandviș",
     "Telemeaua poate fi umplutura unui sandviș, singură sau alături de legume."),
    ("sandvis-friptura", "Pâine", "Friptură", "Sandviș",
     "Feliile de friptură rămase de la masă pot umple un sandviș."),
    ("sandvis-fasole", "Pâine", "Fasole bătută", "Sandviș",
     "Fasolea bătută întinsă pe pâine formează o gustare de tip sandviș deschis."),
    ("sandvis-salata", "Pâine", "Salată", "Sandviș",
     "Salata de legume poate umple un sandviș vegetarian, cu pâine și un sos după gust."),
    ("sandvis-zacusca", "Pâine", "Zacuscă", "Sandviș",
     "Zacusca întinsă pe pâine formează un sandviș deschis de legume."),
    ("sandvis-cascaval", "Pâine", "Cașcaval", "Sandviș",
     "Feliile de cașcaval puse între felii de pâine formează un sandviș."),
    ("sandvis-snitel", "Pâine", "Șnițel", "Sandviș",
     "Șnițelul pus în pâine, cu legume sau sos, devine umplutură de sandviș."),
    ("sandvis-chiftele", "Pâine", "Chiftele", "Sandviș",
     "Chiftelele pot umple un sandviș, alături de legume și sos."),
    ("clatite-tigaie", "Aluat", "Tigaie", "Clătite",
     "Un aluat fluid cu făină, lapte și ou se întinde în tigaie pentru clătite subțiri."),
    ("pizza-rosie", "Aluat", "Roșie", "Pizza",
     "Aluatul întins și sosul din roșii formează baza unei pizza, coaptă cu toppinguri."),
    ("pizza-cascaval", "Aluat", "Cașcaval", "Pizza",
     "Cașcavalul se poate topi peste un blat de pizza din aluat, cu sos și alte ingrediente."),
    ("cartofi-ulei", "Cartof", "Ulei", "Cartofi prăjiți",
     "Cartoful tăiat în bucăți și prăjit în ulei devine cartofi prăjiți."),
    ("cartofi-tigaie", "Cartof", "Tigaie", "Cartofi prăjiți",
     "Cartofii tăiați se pot prăji într-o tigaie cu ulei încins."),
    ("snitel-faina", "Carne", "Făină", "Șnițel",
     "Feliile subțiri de carne trecute prin făină, apoi ou și pesmet, se prăjesc ca șnițele."),
    ("snitel-firimitura", "Carne", "Firimitură", "Șnițel",
     "Firimiturile de pâine uscată, măcinate ca pesmet, acoperă carnea cu ou pentru șnițel pane."),
    ("cascaval-pane-ou", "Cașcaval", "Ou", "Cașcaval pane",
     "Feliile de cașcaval se trec prin făină, ou bătut și pesmet, apoi se prăjesc."),
    ("cascaval-pane-firimitura", "Cașcaval", "Firimitură", "Cașcaval pane",
     "Firimiturile uscate și măcinate pentru pesmet formează crusta cașcavalului pane, "
     "cu făină și ou."),
    ("chiftele-ou", "Carne", "Ou", "Chiftele",
     "Oul ajută să lege carnea tocată cu legume și condimente pentru chiftele."),
    ("chiftele-usturoi", "Carne", "Usturoi", "Chiftele",
     "Carnea tocată aromatizată cu usturoi se poate modela în chiftele și prăji ori coace."),
    ("frigarui-ceapa", "Carne", "Ceapă", "Frigărui",
     "Cuburile de carne și bucățile de ceapă înșirate pe bețe se frig ca frigărui."),
    ("friptura-tigaie", "Carne", "Tigaie", "Friptură",
     "Bucățile de carne pot fi fripte și rumenite în tigaie."),
    ("friptura-gratar", "Carne", "Grătar", "Friptură",
     "Carnea friptă la grătar este o variantă de friptură."),
    ("perisoare-orez", "Carne", "Orez", "Ciorbă de perișoare",
     "Carnea tocată și orezul formează perișoare, legate cu ou și fierte într-o ciorbă."),
    ("piftie-supa", "Supă", "Gelatină alimentară", "Piftie",
     "O supă de carne poate fi închegată cu gelatină și răcită, "
     "cu carne și usturoi, pentru piftie."),
    ("piftie-carne", "Carne", "Gelatină alimentară", "Piftie",
     "Carnea fiartă în zeamă aromată poate fi legată cu gelatină și răcită într-o piftie."),
    ("zacusca-rosie", "Ardei", "Roșie", "Zacuscă",
     "Ardeii copți și roșiile intră în zacuscă, gătite cu ceapă și, "
     "după variantă, vinete sau fasole."),
    ("zacusca-fasole", "Ardei", "Fasole", "Zacuscă",
     "Ardeii copți și fasolea fiartă intră în zacusca de fasole, cu ceapă și roșii."),
    ("fasole-mujdei", "Fasole", "Mujdei", "Fasole bătută",
     "Fasolea fiartă și pasată se poate aromatiza cu mujdei pentru fasole bătută."),
    ("urda-oala", "Zer", "Oală", "Urdă",
     "Zerul încălzit în oală dă flocoane de proteine, care se adună și se scurg ca urdă."),
    ("urda-lamaie", "Zer", "Lămâie", "Urdă",
     "La încălzirea zerului, puțină zeamă de lămâie poate ajuta "
     "coagularea proteinelor pentru urdă."),
    ("papanasi-urda-faina", "Urdă", "Făină", "Papanași",
     "Urda poate înlocui brânza proaspătă într-un aluat de papanași cu făină și ou."),
    ("papanasi-urda-gris", "Urdă", "Griș", "Papanași",
     "Urda poate fi legată cu griș, făină și ou pentru o variantă de papanași copți."),
    ("poale-brau-urda", "Aluat", "Urdă", "Poale-n brâu",
     "Poalele-n brâu pot avea umplutură de urdă îndulcită, învelită în aluat dospit."),
    ("urda-smantana", "Urdă", "Smântână", "Brânză cu smântână",
     "Urda este un produs lactat care poate fi amestecat cu smântână, "
     "ca variantă de brânză cu smântână."),
    ("mucenici-miere", "Aluat", "Miere", "Mucenici",
     "Mucenicii moldovenești se modelează din aluat dospit ca opturi, se coc și se ung cu miere."),
    ("mucenici-paste", "Paste", "Nucă", "Mucenici",
     "Pastele mici în formă de opt se fierb în zeamă dulce cu nucă pentru mucenici muntenești."),
    ("alivenci-branza", "Mălai", "Brânză", "Alivenci",
     "Mălaiul și brânza intră în compoziția de alivenci, coaptă cu ou și alte lactate."),
    ("alivenci-smantana", "Mălai", "Smântână", "Alivenci",
     "Mălaiul și smântâna se combină cu ou și lactate în variante de alivenci coapte."),
    ("cornulete-dulceata", "Aluat", "Dulceață", "Cornulețe",
     "Aluatul fraged rulat în mici cornuri poate înveli o umplutură de dulceață bine scursă."),
    ("cornulete-untura", "Aluat", "Untură", "Cornulețe",
     "Untura frăgezește un aluat modelat în cornulețe, umplute și apoi coapte."),
    ("cornulete-smantana", "Aluat", "Smântână", "Cornulețe",
     "Smântâna intră în unele aluaturi fragede pentru cornulețe cu umplutură dulce."),
    ("turta-faina", "Făină", "Miere", "Turtă dulce",
     "Făina și mierea formează baza aluatului de turtă dulce, cu mirodenii și coacere."),
    ("turta-scortisoara", "Miere", "Scorțișoară", "Turtă dulce",
     "Mierea și scorțișoara dau gust caracteristic turtei dulci, într-un aluat cu făină."),
    ("halva-zahar", "Semințe de floarea-soarelui", "Zahăr", "Halva",
     "Miezul de semințe de floarea-soarelui măcinat se leagă cu sirop de zahăr pentru halva."),
    ("halva-miere", "Semințe de floarea-soarelui", "Miere", "Halva",
     "O variantă de halva de casă leagă semințele de floarea-soarelui măcinate cu miere."),
    ("coliva-nuca", "Arpacaș", "Nucă", "Colivă",
     "Arpacașul fiert, îndulcit și amestecat cu nucă este baza unei colive."),
    ("coliva-zahar", "Arpacaș", "Zahăr", "Colivă",
     "Arpacașul fiert se îndulcește cu zahăr și se completează de obicei cu nucă pentru colivă."),
    ("placinte-dovleac", "Aluat", "Dovleac", "Plăcinte",
     "Aluatul învelește dovleacul ras și pregătit ca umplutură pentru plăcinte."),
    ("placinte-telemea", "Aluat", "Telemea", "Plăcinte",
     "Telemeaua poate umple foi de aluat pentru plăcinte sărate."),
    ("placinte-pruna", "Aluat", "Prună", "Plăcinte",
     "Prunele fără sâmburi pot umple un aluat de plăcintă, îndulcite după gust."),
    ("dulceata-pruna", "Prună", "Zahăr", "Dulceață",
     "Prunele fierte cu zahăr, cu fructele păstrate în bucăți, dau dulceață de prune."),
    ("dulceata-capsuna", "Căpșună", "Zahăr", "Dulceață",
     "Căpșunile fierte cu zahăr dau dulceață de căpșuni."),
    ("compot-pruna", "Prună", "Apă", "Compot",
     "Prunele fierte în apă dau compot de prune, îndulcit după gust."),
    ("compot-capsuna", "Căpșună", "Apă", "Compot",
     "Căpșunile fierte scurt în apă pot fi păstrate în compot, cu zahăr după gust."),
    ("inghetata-iaurt", "Iaurt", "Congelator", "Înghețată",
     "Iaurtul îndulcit, eventual cu fructe, poate fi congelat ca înghețată de iaurt."),
    ("gogosi-iaurt", "Aluat", "Iaurt", "Gogoși",
     "Iaurtul intră în aluaturi moi de gogoși, porționate cu lingura și prăjite."),
    ("supa-oala", "Legume", "Oală", "Supă",
     "Legumele fierte în apă într-o oală dau o supă de legume."),
    ("mamaliga-oala", "Mălai", "Oală", "Mămăligă",
     "Mălaiul se fierbe și se amestecă într-o oală cu apă pentru mămăligă."),
]

GOALS = [
    ("paine", "Pâine", "Prima pâine"),
    ("bulz", "Bulz", "Gust de stână"),
    ("muraturi", "Murături", "Cămara pentru iarnă"),
    ("ciorba-fasole", "Ciorbă de fasole", "O ciorbă de casă"),
    ("cozonac", "Cozonac", "Cozonacul de sărbătoare"),
    ("papanasi", "Papanași", "Papanași pentru desert"),
    ("inghetata", "Înghețată", "Un desert rece"),
    ("diplomat", "Tort Diplomat", "Tortul de sărbătoare"),
    ("sarmale", "Sarmale", "Sarmale pentru masă"),
    ("sandvis", "Sandviș", "O gustare din ce ai descoperit"),
    ("clatite", "Clătite", "Clătite la tigaie"),
    ("pizza", "Pizza", "Pizza de casă"),
    ("snitel", "Șnițel", "Crusta crocantă"),
    ("zacusca", "Zacuscă", "Încă un borcan în cămară"),
    ("urda", "Urdă", "Din zer, o nouă brânză"),
    ("mucenici", "Mucenici", "Opturi dulci"),
    ("cornulete", "Cornulețe", "Cornulețe fragede"),
    ("halva", "Halva", "Dulce din semințe"),
    ("placinte", "Plăcinte", "Plăcinte dulci sau sărate"),
]
