#!/usr/bin/env python3
"""Deterministic, additive KG-content builder for kg_sample.json.

Takes the committed **base** fixture (build_version ``fixture-v2``) plus an authored
expansion (``scripts/expansion_data.json``: new nodes, new edges, candidate puzzle
endpoint pairs) and produces an **expanded** fixture (build_version ``fixture-v3``).

Why a builder (and not hand-edited JSON): the puzzle invariants the committed
``validate_fixture.py`` gate enforces (par == optimal_hops == shortest-path length on
the non-distractor subgraph; hop bands; hint_neighbors == solution_path[1:]; NO
distractor shortcut below par; in-category scope) are easy to get wrong by hand. This
script reuses the validator's OWN direction-aware BFS + bucket scoping to *generate*
puzzles that pass by construction, and it refuses to emit anything out of band.

It is strictly additive and SAFE:
  * existing nodes/edges/puzzles are preserved verbatim (only node ``degree`` is
    recomputed, which the validator does not check and which stays internally
    consistent: degree == incident-edge count, exactly as the base fixture holds);
  * it ABORTS if any newly-added edge would shorten an EXISTING puzzle's start->target
    distance (on its own bucket adjacency) or open a distractor shortcut — i.e. existing
    puzzles can never be silently invalidated.

Idempotent by design: it only runs against a ``fixture-v2`` base. To re-run after
iterating on the expansion data, restore the base first::

    git checkout cat_de_roman_esti/fixtures/kg_sample.json tests/fixtures/kg_sample.json
    python scripts/expand_content.py            # rebuild from base + expansion_data.json

Exit 0 on success (after self-validating GREEN), 1 on any error.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from typing import NoReturn

# Reuse the validator's EXACT traversal + scoping so generated puzzles agree with the
# gate bit-for-bit (same sorted-neighbour BFS, same in-category bucketing).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_fixture import (  # noqa: E402
    CATEGORIES,
    HOP_BANDS,
    MIXED_CATEGORY,
    PACKAGE_FIXTURE,
    TESTS_FIXTURE,
    _bfs_distance,
    _edges_within_category,
    bfs_shortest_path,
    build_adjacency,
    tier_for_salience,
)
from validate_fixture import validate as validate_fixture  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPANSION_DATA = Path(__file__).resolve().parent / "expansion_data.json"

BASE_BUILD_VERSION = "fixture-v2"
NEW_BUILD_VERSION = "fixture-v3"

# Auto-discovery target: how many NEW puzzles to aim for per (category, difficulty)
# bucket (explicit candidates count toward it; mixed uses the full-graph adjacency).
TARGET_NEW_PER_BUCKET = {"easy": 4, "hard": 4}

NEW_NOTE = (
    "Assembled Romanian KG fixture for offline play + tests. v3 ADDITIVELY expands the "
    "v2 base: new per-category nodes/edges + cross-category bridges authored and "
    "adversarially fact-checked, then puzzles regenerated by scripts/expand_content.py "
    "(the same direction-aware BFS shortest-path on the non-distractor subgraph that "
    "validate_fixture.py re-derives). All v1/v2 nodes/edges/puzzles are preserved "
    "verbatim (only node degree is recomputed = incident-edge count); no new edge "
    "shortens an existing puzzle. Field shapes conform to KG_CONTRACT.md v1: easy "
    "optimal_hops in [2,3], hard in [4,7], par==optimal_hops, "
    "hint_neighbors==solution_path[1:]; difficulty_tier from salience bands."
)


def die(msg: str) -> NoReturn:
    print(f"expand_content: ERROR — {msg}", file=sys.stderr)
    sys.exit(1)


def _bucket_adjacencies(edges: list[dict], cat_by_id: dict[str, str]):
    """(play, all) adjacency pickers per the validator's bucket rules."""
    full_play = build_adjacency(edges, include_distractors=False)
    full_all = build_adjacency(edges, include_distractors=True)
    cat_play: dict[str, dict] = {}
    cat_all: dict[str, dict] = {}
    for cat in CATEGORIES:
        in_cat = {nid for nid, c in cat_by_id.items() if c == cat}
        be = _edges_within_category(edges, in_cat)
        cat_play[cat] = build_adjacency(be, include_distractors=False)
        cat_all[cat] = build_adjacency(be, include_distractors=True)

    def pick(cat: str):
        if cat == MIXED_CATEGORY:
            return full_play, full_all
        return cat_play[cat], cat_all[cat]

    return pick


def main() -> int:
    # ---- load base (must be the v2 base, never an already-expanded file) ----
    base_raw = PACKAGE_FIXTURE.read_text(encoding="utf-8")
    data = json.loads(base_raw)
    bv = data.get("meta", {}).get("build_version")
    if bv != BASE_BUILD_VERSION:
        die(
            f"base fixture build_version is {bv!r}, expected {BASE_BUILD_VERSION!r}. "
            "Restore the base first: git checkout "
            "cat_de_roman_esti/fixtures/kg_sample.json tests/fixtures/kg_sample.json"
        )

    if not EXPANSION_DATA.exists():
        die(f"expansion data not found: {EXPANSION_DATA}")
    exp = json.loads(EXPANSION_DATA.read_text(encoding="utf-8"))
    new_nodes_in: list[dict] = exp.get("nodes", [])
    new_edges_in: list[dict] = exp.get("edges", [])
    candidates: list[dict] = exp.get("puzzle_candidates", [])

    nodes: list[dict] = list(data["kg_nodes"])
    edges: list[dict] = list(data["kg_edges"])
    puzzles: list[dict] = list(data["kg_puzzles"])

    existing_node_ids = {n["id"] for n in nodes}
    existing_edge_ids = {e["id"] for e in edges}
    existing_puzzle_ids = {p["id"] for p in puzzles}

    # ---- add new nodes (validate shape + uniqueness + tier band) ----
    seen_new_node_ids: set[str] = set()
    for n in new_nodes_in:
        nid = n["id"]
        if nid in existing_node_ids:
            die(f"new node {nid!r} collides with an existing node id")
        if nid in seen_new_node_ids:
            die(f"duplicate new node id {nid!r} in expansion data")
        if n["category"] not in CATEGORIES:
            die(f"new node {nid!r} category {n['category']!r} not a game category")
        # Round ONCE, then derive the tier from the SAME rounded value the fixture
        # stores — the validator recomputes the tier from the stored (rounded) salience,
        # so deriving it from the unrounded value could diverge at a band boundary.
        sal = round(float(n["salience"]), 4)
        node_rec = {
            "id": nid,
            "node_type": n["node_type"],
            "label_ro": n["label_ro"],
            "category": n["category"],
            "description": n["description"],
            "salience": sal,
            "difficulty_tier": tier_for_salience(sal),
            "degree": 0,  # filled after edges are known
        }
        nodes.append(node_rec)
        seen_new_node_ids.add(nid)

    all_node_ids = existing_node_ids | seen_new_node_ids

    # ---- add new edges (validate refs + assign ids) ----
    edge_seq = 0

    def next_edge_id(distractor: bool) -> str:
        nonlocal edge_seq
        while True:
            edge_seq += 1
            eid = f"{'xd' if distractor else 'xe'}{edge_seq}"
            if eid not in existing_edge_ids:
                return eid

    added_edges: list[dict] = []
    seen_pairs: set[tuple] = set()
    for e in new_edges_in:
        src, dst = e["src"], e["dst"]
        if src not in all_node_ids:
            die(f"new edge src {src!r} is not a known node id")
        if dst not in all_node_ids:
            die(f"new edge dst {dst!r} is not a known node id")
        if src == dst:
            die(f"new edge is a self-loop on {src!r}")
        is_d = int(e.get("is_distractor", 0))
        key = (src, dst, e["relation"], is_d)
        if key in seen_pairs:
            continue  # skip duplicate authored edge
        seen_pairs.add(key)
        rec = {
            "id": next_edge_id(bool(is_d)),
            "src_id": src,
            "dst_id": dst,
            "relation": e["relation"],
            "label_ro": e.get("label_ro", ""),
            "strength": round(float(e.get("strength", 0.5)), 3),
            "is_distractor": is_d,
            "bidirectional": int(e.get("bidirectional", 1)),
        }
        edges.append(rec)
        added_edges.append(rec)

    # ---- recompute degree (= incident-edge count) for ALL nodes ----
    deg: Counter[str] = Counter()
    for e in edges:
        deg[e["src_id"]] += 1
        deg[e["dst_id"]] += 1
    for n in nodes:
        n["degree"] = deg.get(n["id"], 0)

    cat_by_id = {n["id"]: n["category"] for n in nodes}

    # ---- SAFETY: no new edge may shorten an EXISTING puzzle ----
    pick = _bucket_adjacencies(edges, cat_by_id)
    for p in puzzles:
        adj_play, adj_all = pick(p["category"])
        play = _bfs_distance(adj_play, p["start_id"], p["target_id"])
        full = _bfs_distance(adj_all, p["start_id"], p["target_id"])
        want = p["optimal_hops"]
        if play != want:
            die(
                f"a new edge changed existing puzzle {p['id']!r} play-distance "
                f"{p['start_id']}->{p['target_id']} from {want} to {play} — "
                "remove/adjust the offending intra-category edge"
            )
        if full is not None and full < p["par"]:
            die(
                f"a new edge opened a distractor shortcut for existing puzzle "
                f"{p['id']!r}: full-graph distance {full} < par {p['par']}"
            )

    # ---- generate NEW puzzles from candidate endpoint pairs ----
    existing_triples = {
        (p["start_id"], p["target_id"], p["difficulty"]) for p in puzzles
    }
    gen_counter: Counter[tuple] = Counter()
    generated: list[dict] = []
    skipped: list[str] = []

    # Deterministic order: by (category, difficulty, start, target).
    def ckey(c):
        return (
            c.get("category", ""),
            c.get("difficulty", ""),
            c.get("start", ""),
            c.get("target", ""),
        )

    for c in sorted(candidates, key=ckey):
        cat = c["category"]
        diff = c["difficulty"]
        start, target = c["start"], c["target"]
        tag = f"{cat}/{diff} {start}->{target}"
        if cat != MIXED_CATEGORY and cat not in CATEGORIES:
            skipped.append(f"{tag}: unknown category")
            continue
        if diff not in HOP_BANDS:
            skipped.append(f"{tag}: unknown difficulty")
            continue
        if start not in all_node_ids or target not in all_node_ids:
            skipped.append(f"{tag}: endpoint not a known node")
            continue
        if start == target:
            skipped.append(f"{tag}: start == target")
            continue
        if (start, target, diff) in existing_triples:
            skipped.append(f"{tag}: duplicates an existing puzzle")
            continue

        adj_play, adj_all = pick(cat)
        path = bfs_shortest_path(adj_play, start, target)
        if path is None:
            skipped.append(f"{tag}: unreachable on non-distractor {cat} subgraph")
            continue
        hops = len(path) - 1
        lo, hi = HOP_BANDS[diff]
        if not (lo <= hops <= hi):
            skipped.append(f"{tag}: {hops} hops outside {diff} band [{lo},{hi}]")
            continue
        # category scope
        path_cats = {cat_by_id.get(nid) for nid in path}
        if cat == MIXED_CATEGORY:
            if len({c for c in path_cats if c}) < 2:
                skipped.append(f"{tag}: mixed path does not cross >=2 categories")
                continue
        elif path_cats - {cat}:
            skipped.append(f"{tag}: path leaves category {cat}")
            continue
        # no distractor shortcut below par
        full = _bfs_distance(adj_all, start, target)
        if full is not None and full < hops:
            skipped.append(f"{tag}: distractor shortcut ({full} < {hops})")
            continue

        gen_counter[(cat, diff)] += 1
        idx = gen_counter[(cat, diff)]
        pid = f"pz_x_{cat}_{diff}_{idx}"
        while pid in existing_puzzle_ids:
            idx += 1
            pid = f"pz_x_{cat}_{diff}_{idx}"
        sal = {n["id"]: n["salience"] for n in nodes}
        generated.append(
            {
                "id": pid,
                "start_id": start,
                "target_id": target,
                "category": cat,
                "difficulty": diff,
                "optimal_hops": hops,
                "par": hops,
                "solution_path": list(path),
                "hint_neighbors": list(path[1:]),
                "start_salience": round(float(sal[start]), 4),
                "target_salience": round(float(sal[target]), 4),
            }
        )
        existing_triples.add((start, target, diff))

    # ---- AUTO-DISCOVERY: enrich each bucket with in-band pairs FEATURING the new
    #      nodes, so the expansion adds a fuller, even spread of puzzles (not just the
    #      few explicit pairs that happened to land in band). Same correctness gates. ----
    sal_by = {n["id"]: n["salience"] for n in nodes}
    nodes_by_cat: dict[str, list[str]] = {}
    for nid, ccat in cat_by_id.items():
        nodes_by_cat.setdefault(ccat, []).append(nid)
    all_ids_sorted = sorted(cat_by_id)
    SALIENCE_ANCHOR = 0.40  # at least one endpoint must be reasonably recognizable

    def emit(cat: str, diff: str, start: str, target: str, path: list[str]) -> None:
        nonlocal generated
        hops = len(path) - 1
        gen_counter[(cat, diff)] += 1
        idx = gen_counter[(cat, diff)]
        pid = f"pz_x_{cat}_{diff}_{idx}"
        while pid in existing_puzzle_ids or any(g["id"] == pid for g in generated):
            idx += 1
            pid = f"pz_x_{cat}_{diff}_{idx}"
        generated.append(
            {
                "id": pid,
                "start_id": start,
                "target_id": target,
                "category": cat,
                "difficulty": diff,
                "optimal_hops": hops,
                "par": hops,
                "solution_path": list(path),
                "hint_neighbors": list(path[1:]),
                "start_salience": round(float(sal_by[start]), 4),
                "target_salience": round(float(sal_by[target]), 4),
            }
        )
        existing_triples.add((start, target, diff))

    for cat in list(CATEGORIES) + [MIXED_CATEGORY]:
        adj_play, adj_all = pick(cat)
        pool = sorted(nodes_by_cat.get(cat, [])) if cat != MIXED_CATEGORY else all_ids_sorted
        for diff in ("easy", "hard"):
            lo, hi = HOP_BANDS[diff]
            need = TARGET_NEW_PER_BUCKET[diff] - gen_counter[(cat, diff)]
            if need <= 0:
                continue
            found: list[tuple] = []
            for i, a in enumerate(pool):
                for b in pool[i + 1 :]:
                    # FEATURE the expansion: at least one endpoint must be a new node.
                    if a not in seen_new_node_ids and b not in seen_new_node_ids:
                        continue
                    if max(sal_by[a], sal_by[b]) < SALIENCE_ANCHOR:
                        continue
                    if (a, b, diff) in existing_triples or (b, a, diff) in existing_triples:
                        continue
                    path = bfs_shortest_path(adj_play, a, b)
                    if path is None:
                        continue
                    hops = len(path) - 1
                    if not (lo <= hops <= hi):
                        continue
                    pcats = {cat_by_id.get(n) for n in path}
                    if cat == MIXED_CATEGORY:
                        if len({c for c in pcats if c}) < 2:
                            continue
                    elif pcats - {cat}:
                        continue
                    full = _bfs_distance(adj_all, a, b)
                    if full is not None and full < hops:
                        continue
                    found.append((a, b, path))
            # most-recognizable first, deterministic tie-break
            found.sort(key=lambda x: (-(sal_by[x[0]] + sal_by[x[1]]), x[0], x[1]))
            for a, b, path in found[:need]:
                if (a, b, diff) in existing_triples or (b, a, diff) in existing_triples:
                    continue
                emit(cat, diff, a, b, path)

    puzzles.extend(generated)

    # ---- rebuild meta counts ----
    by_cat = dict(sorted(Counter(n["category"] for n in nodes).items()))
    pcd = dict(sorted(Counter(f"{p['category']}/{p['difficulty']}" for p in puzzles).items()))
    data["meta"]["build_version"] = NEW_BUILD_VERSION
    data["meta"]["note"] = NEW_NOTE
    data["meta"]["counts"] = {
        "nodes": len(nodes),
        "edges": len(edges),
        "puzzles": len(puzzles),
        "by_category": by_cat,
        "puzzles_by_cat_diff": pcd,
    }
    data["kg_nodes"] = nodes
    data["kg_edges"] = edges
    data["kg_puzzles"] = puzzles

    # Snapshot the on-disk base so a failed self-validation can roll back (never leave a
    # broken fixture committed to either copy).
    pkg_base = PACKAGE_FIXTURE.read_text(encoding="utf-8")
    tests_base = TESTS_FIXTURE.read_text(encoding="utf-8")

    out = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    PACKAGE_FIXTURE.write_text(out, encoding="utf-8")
    TESTS_FIXTURE.write_text(out, encoding="utf-8")

    # ---- report ----
    print("expand_content: wrote both fixture copies")
    print(f"  nodes:   +{len(seen_new_node_ids):<3} -> {len(nodes)}")
    print(f"  edges:   +{len(added_edges):<3} -> {len(edges)}")
    print(f"  puzzles: +{len(generated):<3} -> {len(puzzles)}")
    print("  new puzzles by bucket:", dict(sorted(gen_counter.items())))
    if skipped:
        print(f"  skipped {len(skipped)} candidate(s):")
        for s in skipped:
            print(f"    - {s}")

    # ---- self-validate (must be GREEN); roll back BOTH copies on failure ----
    errors = validate_fixture(PACKAGE_FIXTURE)
    if errors:
        PACKAGE_FIXTURE.write_text(pkg_base, encoding="utf-8")
        TESTS_FIXTURE.write_text(tests_base, encoding="utf-8")
        print(
            f"\nexpand_content: VALIDATION FAILED ({len(errors)} error(s)) — "
            "rolled back both fixture copies to the base:",
            file=sys.stderr,
        )
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print("\nexpand_content: GREEN — expanded fixture is valid.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
