"""Export validated, private Intrusul content for the native Go pilot.

Python remains the content-validation authority. This file is a build input,
never a browser/mobile asset. --check detects any source or export drift.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections.abc import Mapping
from pathlib import Path

from cat_de_roman_esti import __version__
from cat_de_roman_esti.data import fixture_manifest
from cat_de_roman_esti.wordgames.categories import CATEGORY_LABELS
from cat_de_roman_esti.wordgames.derived_catalog import get_derived_catalog
from cat_de_roman_esti.wordgames.service import get_service

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "go-backend/internal/content/bundled.json"
PIN = OUTPUT.with_name("digest.go")
SOURCES = (
    "kg_sample.json",
    "derived_catalog_v38.json",
    "quick_games_v92.json",
    "board_rankings_v37.json",
    "release_reserve_v1.json",
    "games_pack.json",
)


def plain(value: object) -> object:
    if isinstance(value, Mapping):
        return {str(key): plain(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [plain(item) for item in value]
    return value


def export_bytes() -> bytes:
    if any(
        os.environ.get(name)
        for name in (
            "CAT_KG_FIXTURE",
            "CAT_GAMES_PACK",
            "CAT_BOARD_RANKINGS",
        )
    ):
        raise ValueError("Go export requires bundled content without source overrides")
    service = get_service()
    catalog = get_derived_catalog()  # verifies ranking, KG, payload and reserve identities
    payload = {
        "schema_version": 1,
        "app_version": __version__,
        "sources": {
            name: hashlib.sha256(
                (ROOT / "cat_de_roman_esti/fixtures" / name)
                .read_bytes()
                .replace(b"\r\n", b"\n")
                .replace(b"\r", b"\n")
            ).hexdigest()
            for name in SOURCES
        },
        "labels": {node_id: service.display_label(node_id) for node_id in service.all_ids()},
        "category_labels": CATEGORY_LABELS,
        "manifest": fixture_manifest(),
        "boards": [
            {
                "game": board.game,
                "catalog_id": board._catalog_id,
                "source_id": board._source_id,
                "category": board.category,
                "difficulty": board.difficulty,
                "overall_score": board._standard_score,
                "starter_score": board._starter_score,
                "overall_rank": board._standard_rank,
                "starter_rank": board._starter_rank,
                "starter_safe": board._starter_eligible,
                "payload": plain(board.payload),
            }
            for board in catalog.pool("intrusul")
        ],
    }
    return (
        json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n"
    ).encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = export_bytes()
    pin = (
        "// Code generated by scripts/export_go_content.py; DO NOT EDIT.\n"
        "package content\n\n"
        f'const bundledSHA256 = "{hashlib.sha256(expected).hexdigest()}"\n'
    ).encode()
    if args.check:
        if (
            not OUTPUT.is_file()
            or OUTPUT.read_bytes() != expected
            or not PIN.is_file()
            or PIN.read_bytes() != pin
        ):
            parser.exit(1, "Go private content is stale; run scripts/export_go_content.py.\n")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_bytes(expected)
        PIN.write_bytes(pin)
    print(f"Go private content {'current' if args.check else 'exported'}: {len(expected)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
