"""V90 household proposal; apply only after exact independent graph review.

The supported common-word applicator owns generated fixture writes. New hidden
rounds are separately reviewed and staged; this module contains no game records.
"""
from __future__ import annotations

from basic_words_v33_data import BEGINNER_BENCHMARK as BEGINNER_BENCHMARK
from contexto_common_words_v72_data import (
    DEFERRED_AMBIGUOUS_TERMS as DEFERRED_AMBIGUOUS_TERMS,
)

BUILD_VERSION = "fixture-v90-household-discovery"
NOTE = "v90: three household/food concepts, ten grammatical forms and seventeen directed links."
GAME_ITEM_IDS: tuple[str, ...] = ()

NODES = ({'id': 'n_v90_household_praf',
  'label_ro': 'Praf',
  'category': 'viata_de_roman',
  'description': 'Particule fine care plutesc în aer sau se depun pe suprafețe; aici, sensul '
                 'de praf adunat la curățenie, nu pulberile alimentare.',
  'aliases': ['praful', 'prafului'],
  'node_type': 'concept',
  'salience': 0.9},
 {'id': 'n_v90_food_firimitura',
  'label_ro': 'Firimitură',
  'category': 'gastronomie',
  'description': 'Bucățică foarte mică desprinsă din pâine sau din alt aliment, de exemplu '
                 'dintr-un biscuit.',
  'aliases': ['firimituri', 'firimiturile', 'firimiturii', 'firimiturilor'],
  'node_type': 'concept',
  'salience': 0.9},
 {'id': 'n_v90_textile_scama',
  'label_ro': 'Scamă',
  'category': 'viata_de_roman',
  'description': 'Fir textil scurt desprins dintr-o țesătură, întâlnit pe haine și pe '
                 'textilele din casă.',
  'aliases': ['scame', 'scamele', 'scamei', 'scamelor'],
  'node_type': 'concept',
  'salience': 0.85})

EDGES = ({'src': 'n_v90_household_praf',
  'dst': 'n_v31_cleaning_floor_faras',
  'relation': 'collected_with',
  'label_ro': 'se adună cu fărașul',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v90_household_praf',
  'dst': 'n_v88_cleaning_matura',
  'relation': 'swept_with',
  'label_ro': 'se strânge de pe podea cu mătura',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v90_household_praf',
  'dst': 'n_v31_cleaning_floor_mop',
  'relation': 'collected_with',
  'label_ro': 'poate fi colectat de pe podea de un mop cu microfibre',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v90_household_praf',
  'dst': 'n_v31_cleaning_floor_aspirator',
  'relation': 'collected_with',
  'label_ro': 'se îndepărtează prin aspirare cu',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.9},
 {'src': 'n_v4gas_paine',
  'dst': 'n_v90_food_firimitura',
  'relation': 'crumbles_into',
  'label_ro': 'lasă bucățele mici când se taie sau se rupe',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v24_food_snack_biscuit',
  'dst': 'n_v90_food_firimitura',
  'relation': 'crumbles_into',
  'label_ro': 'poate lăsa bucățele mici la rupere sau consum',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v90_food_firimitura',
  'dst': 'n_v31_cleaning_floor_faras',
  'relation': 'collected_with',
  'label_ro': 'se adună de pe podea cu fărașul',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v90_food_firimitura',
  'dst': 'n_v31_cleaning_floor_aspirator',
  'relation': 'collected_with',
  'label_ro': 'se îndepărtează de pe podele sau covoare cu',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v29_clothing_everyday_haina',
  'dst': 'n_v90_textile_scama',
  'relation': 'may_shed',
  'label_ro': 'poate lăsa fire textile scurte pe suprafață',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v24_home_textiles_patura',
  'dst': 'n_v90_textile_scama',
  'relation': 'may_shed',
  'label_ro': 'poate forma fire textile scurte desprinse',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v24_home_textiles_covor',
  'dst': 'n_v90_textile_scama',
  'relation': 'may_shed',
  'label_ro': 'unele covoare, mai ales din lână, lasă fire textile scurte',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v90_textile_scama',
  'dst': 'n_v31_cleaning_floor_aspirator',
  'relation': 'collected_with',
  'label_ro': 'se îndepărtează de pe podele și covoare prin aspirare cu',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v24_home_textiles_covor',
  'dst': 'n_v31_cleaning_floor_aspirator',
  'relation': 'cleaned_with',
  'label_ro': 'se curăță periodic prin aspirare cu',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v3sti_electricitate',
  'dst': 'n_v31_cleaning_floor_aspirator',
  'relation': 'powers',
  'label_ro': 'asigură energia de funcționare, din rețea sau acumulator',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.85},
 {'src': 'n_v30_kitchen_table_farfurie',
  'dst': 'n_v31_cleaning_dishes_burete_vase',
  'relation': 'cleaned_with',
  'label_ro': 'se poate spăla manual cu un burete de vase potrivit suprafeței',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v4gas_apa',
  'dst': 'n_v31_cleaning_dishes_burete_vase',
  'relation': 'used_with',
  'label_ro': 'umezește și clătește buretele folosit la spălarea vaselor',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.8},
 {'src': 'n_v24_home_textiles_covor',
  'dst': 'n_v90_household_praf',
  'relation': 'may_shed',
  'label_ro': 'poate contribui cu fibre la praful din casă',
  'bidirectional': 0,
  'is_distractor': 0,
  'strength': 0.7})

NEW_NODE_IDS = tuple(node["id"] for node in NODES)
INTUITIVE_PAIRS = tuple((edge["src"], edge["dst"]) for edge in EDGES)


def build_nodes_and_edges() -> dict[str, object]:
    return {"nodes": list(NODES), "edges": list(EDGES), "aliases": {}}
